DELETE FROM users;
DELETE FROM categories;
DELETE FROM locations;
DELETE FROM events;
DELETE FROM compilationEvents;
DELETE FROM compilations;
DELETE FROM ParticipationRequests;

ALTER TABLE users ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE categories ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE locations ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE events ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE compilations ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE ParticipationRequests ALTER COLUMN ID RESTART WITH 1;