CREATE TABLE if not exists endpointhit
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app                VARCHAR(64) NOT NULL,
    uri                VARCHAR(64) NOT NULL,
    ip                 VARCHAR(64) NOT NULL,
    timestamp          TIMESTAMP WITHOUT TIME ZONE NOT NULL
);